// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Data;

namespace ServerApp.Migrations
{
    [DbContext(typeof(OtelContext))]
    [Migration("20210708191551_addGuest1")]
    partial class addGuest1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ServerApp.Models.Guest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adi")
                        .HasColumnType("TEXT");

                    b.Property<string>("heskodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("notlar")
                        .HasColumnType("TEXT");

                    b.Property<int>("odano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("secret")
                        .HasColumnType("TEXT");

                    b.Property<string>("soyadi")
                        .HasColumnType("TEXT");

                    b.Property<string>("tckimlikno")
                        .HasColumnType("TEXT");

                    b.Property<int>("ucret")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
